version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bookmak
      POSTGRES_PASSWORD: bookmak
      POSTGRES_DB: bookmak
    volumes:
      - ./data:/var/lib/postgresql/data
  node:
    build: .
    container_name: node
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: bookmak
      DB_USERNAME: bookmak
      DB_PASSWORD: bookmak
      DB_SYNCHRONIZE: false
      DB_LOGGING: true
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      ENABLE_SECURE_COOKIE: false
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}